import { Inter } from 'next/font/google';
import './globals.css';
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cafe Shop Management',
  description: 'Generated by SEIREY Leanghak.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="/cafe_shop_management_logo.jpg"
        type="image/x-icon"
      />
      <title>Cafe Shop Management</title>
      <body className={inter.className}>
        <NextTopLoader color="red" />
        {children}
      </body>
    </html>
  )
}
